export const dom = {
  navTabs: document.querySelectorAll(".nav-tab"),
  screenViews: document.querySelectorAll(".screen-view"),
  navBrand: document.getElementById("navBrand"),
  btnHeroOpenExisting: document.getElementById("btnHeroOpenExisting"),
  btnRawOpenFolder: document.getElementById("btnRawOpenFolder"),
  btnAiOpenFolder: document.getElementById("btnAiOpenFolder"),
  btnEmptyOpenFolder: document.getElementById("btnEmptyOpenFolder"),

  // Tab 1: Extractor
  extractorZipInput: document.getElementById("extractorZipInput"),
  lblChooseZip: document.getElementById("lblChooseZip"),
  selectedZipFilename: document.getElementById("selectedZipFilename"),
  btnStartExportPipeline: document.getElementById("btnStartExportPipeline"),

  // Tab 2: Raw Browser
  rawBrowserToolbar: document.getElementById("rawBrowserToolbar"),
  rawCategoryFilterGroup: document.getElementById("rawCategoryFilterGroup"),
  rawSortOrderSelect: document.getElementById("rawSortOrder"),
  btnToggleRawDates: document.getElementById("btnToggleRawDates"),
  rawTimelineCard: document.getElementById("rawTimelineCard"),
  rawSliderBox: document.getElementById("rawSliderBox"),
  rawSliderHighlight: document.getElementById("rawSliderHighlight"),
  rawTimelineSliderFrom: document.getElementById("rawTimelineSliderFrom"),
  rawTimelineSliderTo: document.getElementById("rawTimelineSliderTo"),
  rawTimelineRangeLabel: document.getElementById("rawTimelineRangeLabel"),
  rawDateFromInput: document.getElementById("rawDateFromInput"),
  rawDateToInput: document.getElementById("rawDateToInput"),
  btnResetRawDates: document.getElementById("btnResetRawDates"),

  rawGrid: document.getElementById("rawGrid"),
  rawEmptyState: document.getElementById("rawEmptyState"),
  rawEmptyMessage: document.getElementById("rawEmptyMessage"),
  rawEmptyCtaGroup: document.getElementById("rawEmptyCtaGroup"),

  rawTopPagination: document.getElementById("rawTopPagination"),
  rawBottomPagination: document.getElementById("rawBottomPagination"),
  rawPageRangeTextTop: document.getElementById("rawPageRangeTextTop"),
  rawPageRangeTextBottom: document.getElementById("rawPageRangeTextBottom"),
  rawPageJumpTop: document.getElementById("rawPageJumpTop"),
  rawPageJumpBottom: document.getElementById("rawPageJumpBottom"),
  rawPageTotalTop: document.getElementById("rawPageTotalTop"),
  rawPageTotalBottom: document.getElementById("rawPageTotalBottom"),
  btnRawPrevPageTop: document.getElementById("btnRawPrevPageTop"),
  btnRawPrevPageBottom: document.getElementById("btnRawPrevPageBottom"),
  btnRawNextPageTop: document.getElementById("btnRawNextPageTop"),
  btnRawNextPageBottom: document.getElementById("btnRawNextPageBottom"),

  // Tab 3: AI Search
  cloudScannerCard: document.getElementById("cloudScannerCard"),
  localHostBanner: document.getElementById("localHostBanner"),
  cloudZipInput: document.getElementById("cloudZipInput"),
  lblCloudZip: document.getElementById("lblCloudZip"),
  btnStartCloudScan: document.getElementById("btnStartCloudScan"),
  aiSearchInput: document.getElementById("aiSearchInput"),
  btnClearAiSearch: document.getElementById("btnClearAiSearch"),
  aiIndexStatus: document.getElementById("aiIndexStatus"),
  aiCategoryFilterGroup: document.getElementById("aiCategoryFilterGroup"),
  aiSortOrderSelect: document.getElementById("aiSortOrder"),
  btnToggleAiDates: document.getElementById("btnToggleAiDates"),

  aiTimelineCard: document.getElementById("aiTimelineCard"),
  aiSliderBox: document.getElementById("aiSliderBox"),
  aiSliderHighlight: document.getElementById("aiSliderHighlight"),
  aiTimelineSliderFrom: document.getElementById("aiTimelineSliderFrom"),
  aiTimelineSliderTo: document.getElementById("aiTimelineSliderTo"),
  aiTimelineRangeLabel: document.getElementById("aiTimelineRangeLabel"),
  aiDateFromInput: document.getElementById("aiDateFromInput"),
  aiDateToInput: document.getElementById("aiDateToInput"),
  btnResetAiDates: document.getElementById("btnResetAiDates"),

  aiGrid: document.getElementById("aiGrid"),
  aiEmptyState: document.getElementById("aiEmptyState"),
  aiEmptyMessage: document.getElementById("aiEmptyMessage"),

  aiPageRangeTextTop: document.getElementById("aiPageRangeTextTop"),
  aiPageRangeTextBottom: document.getElementById("aiPageRangeTextBottom"),
  aiPageJumpTop: document.getElementById("aiPageJumpTop"),
  aiPageJumpBottom: document.getElementById("aiPageJumpBottom"),
  aiPageTotalTop: document.getElementById("aiPageTotalTop"),
  aiPageTotalBottom: document.getElementById("aiPageTotalBottom"),
  btnAiPrevPageTop: document.getElementById("btnAiPrevPageTop"),
  btnAiPrevPageBottom: document.getElementById("btnAiPrevPageBottom"),
  btnAiNextPageTop: document.getElementById("btnAiNextPageTop"),
  btnAiNextPageBottom: document.getElementById("btnAiNextPageBottom"),

  // Modals & Trackers
  supportModal: document.getElementById("supportModal"),
  modalTag: document.getElementById("modalTag"),
  modalTitle: document.getElementById("modalTitle"),
  modalBody: document.getElementById("modalBody"),
  btnOpenSupportModal: document.getElementById("btnOpenSupportModal"),
  btnOpenLocalDemoInfo: document.getElementById("btnOpenLocalDemoInfo"),
  btnCloseSupportModal: document.getElementById("btnCloseSupportModal"),

  browserWarningModal: document.getElementById("browserWarningModal"),
  btnCloseBrowserWarning: document.getElementById("btnCloseBrowserWarning"),
  btnAcknowledgeBrowserWarning: document.getElementById("btnAcknowledgeBrowserWarning"),

  downloadStatusBar: document.getElementById("downloadStatusBar"),
  dlStatusTitle: document.getElementById("dlStatusTitle"),
  dlStatusDetail: document.getElementById("dlStatusDetail"),
  dlProgressBar: document.getElementById("dlProgressBar"),
  btnViewLive: document.getElementById("btnViewLive"),

  // Lightbox
  lightbox: document.getElementById("lightbox"),
  btnCloseLightbox: document.getElementById("btnCloseLightbox"),
  btnLightboxPrev: document.getElementById("btnLightboxPrev"),
  btnLightboxNext: document.getElementById("btnLightboxNext"),
  lightboxMediaPane: document.getElementById("lightboxMediaPane"),
  mediaContainer: document.getElementById("mediaContainer"),
  lightboxFilename: document.getElementById("lightboxFilename"),
  lightboxTimestamp: document.getElementById("lightboxTimestamp"),
  lightboxSubfolder: document.getElementById("lightboxSubfolder"),
  paneVisualTagsSection: document.getElementById("paneVisualTagsSection"),
  paneOcrTextSection: document.getElementById("paneOcrTextSection"),
  lightboxVisualTags: document.getElementById("lightboxVisualTags"),
  lightboxOcrText: document.getElementById("lightboxOcrText"),

  // Counters
  rawCntImg: document.getElementById("rawCntImg"),
  rawCntVid: document.getElementById("rawCntVid"),
  rawCntAud: document.getElementById("rawCntAud"),
  rawCntDoc: document.getElementById("rawCntDoc"),
  rawCntOth: document.getElementById("rawCntOth"),
  aiCntImg: document.getElementById("aiCntImg"),
  aiCntVid: document.getElementById("aiCntVid"),
  aiCntAud: document.getElementById("aiCntAud"),
  aiCntDoc: document.getElementById("aiCntDoc"),
  aiCntOth: document.getElementById("aiCntOth")
};